apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-deployment
  labels:
    app: node-todo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-todo
  template:
    metadata:
      labels:
        app: node-todo
    spec:
      containers:
      - name: todo-app
        image: shailendrasharma9125/node-todo-app:1.0
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: todo-service
spec:
  type: NodePort
  selector:
    app: node-todo
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 31000
